#!/bin/bash
set -ex

[[ $UID != 0 ]] && exec sudo -E "$(readlink -f "$0")" "$@"

up() {
    ip netns add wgns
    ip link add wg0 type wireguard
    ip link set wg0 netns wgns
    ip -n wgns addr add 10.252.1.3/32 dev wg0
    ip netns exec wgns wg setconf wg0 /etc/wireguard/chromium.conf
    ip -n wgns link set wg0 up
    ip -n wgns route add default dev wg0
}

down() {
    ip -n wgns link del wg0
    ip netns delete wgns
}

execi() {
    exec ip netns exec wgns sudo -E -u \#${SUDO_UID:-$(id -u)} -g \#${SUDO_GID:-$(id -g)} -- "$@"
}

command="$1"
shift

case "$command" in
    up) up "$@" ;;
    down) down "$@" ;;
    exec) execi "$@" ;;
    *) echo "Usage: $0 up|down|exec" >&2; exit 1 ;;
esac
